name: .NET Build, Test and Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test with coverage
      run: |
        dotnet test Proyecto_barberia.Tests\Proyecto_barberia.Tests.csproj `
          --configuration Release `
          --no-build `
          /p:CollectCoverage=true `
          /p:CoverletOutputFormat=cobertura `
          /p:CoverletOutput=TestResults/coverage.cobertura.xml
      
    - name: List files (debug)
      run: dir /s coverage.cobertura.xml
      
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: Proyecto_barberia.Tests/TestResults/coverage.cobertura.xml
