name: Build Windows Docker Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Restore NuGet packages
        run: nuget restore "Proyecto barberia.slnx"
      
      - name: Build solution
        run: msbuild "Proyecto barberia.slnx" /p:Configuration=Release
      
      - name: Build Docker image
        run: docker build -f Dockerfile -t galactic10/barberia-app:latest .
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Push to Docker Hub
        run: docker push galactic10/barberia-app:latest